$ReleaseTag = "v1.0.0"
$ReleaseTitle = "v1.0.0 - Innioasis Y1 AirPods 2 Fix Community ROM"
$ReleaseNotes = "release-notes/v1.0.0-community-rom.md"
$ReleaseDir = "D:\Y1-firmware-lab\release"
$RomAsset = Join-Path $ReleaseDir "innioasis-y1-3.0.7-airpods2-fix-community-rom-v1.0.0.zip"
$ChecksumAsset = Join-Path $ReleaseDir "SHA256SUMS.txt"

Write-Host "GitHub Release draft information"
Write-Host ""
Write-Host "Tag: $ReleaseTag"
Write-Host "Title: $ReleaseTitle"
Write-Host "Release notes: $ReleaseNotes"
Write-Host ""
Write-Host "Upload assets manually:"
Write-Host "- $RomAsset"
Write-Host "- $ChecksumAsset"
Write-Host ""
Write-Host "Asset filenames:"
Write-Host "- innioasis-y1-3.0.7-airpods2-fix-community-rom-v1.0.0.zip"
Write-Host "- SHA256SUMS.txt"
Write-Host ""
Write-Host "This script does not call GitHub APIs, gh, upload, or publish anything."
